config/routes.rb
Sorter::Application.routes.draw do
  resources :cars do
    resources :drivers
    
  end
 

   root :to => 'cars#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :drivers
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  belongs_to :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end
  def show
    @car = Car.find(params[:id])
  end
  def new
    @car = Car.new
  end
  def create
    @car = Car.new(params[:car])
    @car.save
    redirect_to @car
  end
  def edit
    @car = Car.find(params[:id])
  end
  def update
    @car = Car.find(params[:id])
    @car.update_attributes(params[:car])
    redirect_to @car    
  end
  def destroy 
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
    @car = Car.find(params[:car_id])
    @driver = @car.drivers.find(params[:driver])
  end
  def show
    @car = Car.find(params[:car_id])
    @driver = @car.drivers.find(params[:driver])
  end
  def edit
    @car = Car.find(params[:car_id])
    @driver = @car.drivers.find(params[:id])
  end
  #def update
  #end
  #def new
  #end
  def create
    @car = Car.find(params[:car_id])
    @driver = @car.drivers.create(params[:driver])
    redirect_to car_path(@car)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/cars/_form.html.erb
<%= form_for @car do |f| %>
  <%= f.label :color %>
  <%= f.text_field :color %>
  <br />
  <%= f.label :make %>
  <%= f.text_field :make %>
  <br />
  <%= f.label :model %>
  <%= f.text_field :model %>
  <br />
  <%= f.label :year %>
  <%= f.text_field :year %>
  <br />
  <%= f.submit %>
<% end %>

app/views/cars/edit.html.erb
<h2> Edit Car </h2>
<%= render 'form' %>

app/views/cars/index.html.erb
<h2> Cars Listing </h2>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Color</th>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
    </tr>
  </thead>
  <tbody>
  <% @cars.each do |car| %>
    <tr>
      <td><%= link_to car.id, car %></td>
      <td><%= car.color %></td>
      <td><%= car.make %></td>
      <td><%= car.model %></td>
      <td><%= car.year %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New', new_car_path %>

app/views/cars/new.html.erb
<h2> New Car </h2>
<%= render 'form' %>

app/views/cars/show.html.erb
<h2> Car Detail </h2>

ID: <%= @car.id %><br />
Color: <%= @car.color %><br />
Make: <%= @car.make %><br />
Model: <%= @car.model %><br />
Year: <%= @car.year %><br />
<br />
<br />
<h3>Drivers:</h3>
<%= render @car.drivers %>
<h2>Add a driver</h2>
<%= render "drivers/form" %>
<%=link_to 'Index', cars_path%>
<%=link_to 'Edit', edit_car_path %>
<%= link_to 'Delete', car_path(@car, :destroy => true), :confirm =>"Are you sure?", :method => :delete %>

app/views/drivers/_driver.html.erb
Name: <%= driver.name %><br />
Team: <%= driver.team %><br />
<%= link_to 'Edit', edit_car_driver_path(@car.id, driver.id) %>
<br />

app/views/drivers/_form.html.erb
<%= form_for([@car, @car.drivers.build]) do |f|%>
  <%= f.label :name %><br />
  <%= f.text_field :name %><br />
  <%= f.label :team %><br />
  <%= f.text_field :team %><br />
  <%= f.submit %>
<% end %>

app/views/drivers/edit.html.erb
<h1> Edit Driver </h1>
<%= form_for([@car, @driver]) do |f|%>
  <%= f.label :name %><br />
  <%= f.text_field :name %><br />
  <%= f.label :team %><br />
  <%= f.text_field :team %><br />
  <%= f.submit %>
<% end %>

app/views/drivers/show.html.erb
<h2> Driver Detail </h2>
#-Name:<%= @driver.name %><br />
#-Team:<%= @driver.team %><br />

<%#- link_to 'Edit', edit_cars_driver_path %>
<%= form_for([@car, @car.drivers.build]) do |f|%>
  <%= f.label :name %><br />
  <%= f.text_field :name %><br />
  <%= f.label :team %><br />
  <%= f.text_field :team %><br />
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sorter</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>